package foo.bar.sample.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;

class GeneratedTypeTest {
    @Test
    @DisplayName("Matcher should not be generated by for types generated by JavaPoetMatcherGenerator")
    void testGenerate_MatcherShouldNotBeGeneratedByForTypesGeneratedByJavaPoetMatcherGenerator()
            throws Exception {
        assertThat(getClass().getResource("/foo/bar/sample/model/GeneratedByJavaPoetMatcherGeneratorTypeMatcher.class"), is(nullValue()));
    }

}